packages:
  - "packages/*"
  - "examples/*"

catalog:
  "@iconify/json": "^2.2.321"
  "@types/fs-extra": "^11.0.4"
  "@vitejs/plugin-vue": "^5.2.1"
  "@vue/tsconfig": "^0.7.0"
  "@vueuse/core": "^13.0.0"
  "fs-extra": "^11.3.0"
  "vite": "^6.1.0"
  "vue": "^3.5.13"
  "vue-tsc": "^2.2.4"
  "sass-embedded": "^1.85.1"
  "typescript": "~5.7.2"
  "picocolors": "^1.1.1"
